<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="design.css">
</head>
<body>

<header>
     <!-- Adjust the path and size as needed -->
    <h1>
    <img src="adminlogo.png" alt="Admin Logo" class="logo">
    Admin Dashboard
</h1>
    
    <nav>
    <a href="/main"><i class="bi bi-house"></i> Home</a>
    <a href="/admin_dashboard"><i class="bi bi-speedometer2"></i> Dashboard</a>
    <a href="/main"><i class="bi bi-box-arrow-right"></i> Logout</a>
</nav>
    <button class="btn" id="toggleSidebarBtn">
            <i class="bi bi-list"></i>
        </button>
</header>

<div class="main-container">
    <div id="sidebar" class="sidebar">
        <a href="/view-quotations"><i class="bi bi-file-earmark-text"></i> Quotations</a>
        <a href="/approved-quotations"><i class="bi bi-check-circle"></i> Approved Quotations</a>
        <a href="/rejected-quotations"><i class="bi bi-x-circle"></i> Rejected Quotations</a>
		<a href="/quotation-bids"><i class="bi bi-check-circle"></i>Quotation bids</a>
        <a href="/manage-inventory"><i class="bi bi-box"></i> Manage Inventory</a>
        
    </div>

    <div class="content d-flex">
        <div class="welcome-image" style="flex: 1; display: flex; align-items: center; justify-content: center;">
            <img src="admin_panel.png" alt="Admin Dashboard Image" style="max-width: 100%; height: auto;"/> <!-- Adjust image size -->
        </div>
        <div class="description" style="flex: 1; padding: 20px;">
            <h5 style="color: #800080;">As an Admin, your responsibilities include:</h5>
            <ul>
                <li>Checking and managing the inventory: You can monitor stock levels, reorder supplies, and ensure that the inventory is accurate and up-to-date.</li>
                <li>Approving or modifying quotations generated by employees: Review the quotations submitted by your team, making adjustments as necessary to meet budgetary or project requirements.</li>
                <li>Confirming orders with vendors: After approving quotations, you can liaise with suppliers to finalize orders, ensuring that all terms are clear and agreed upon.</li>
                <li>Generating reports on procurement activities: Utilize the dashboard to create reports that help analyze spending trends and supplier performance over time.</li>
                <li>Monitoring employee performance and tasks: Keep track of your team's workload and productivity, providing support and guidance as needed.</li>
            </ul>
        </div>
    </div>
</div>
  


<footer>
    &copy; 2024-ProMS All rights reserved
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-IF3gY5L8pE+DZ+8R41/m6kF8Pzm3EzH91A2u7Tz7RlIh3Hx3tb4BfG8S1lAyZFd4"
        crossorigin="anonymous"></script>
    <script>
        document.getElementById('toggleSidebarBtn').addEventListener('click', function() {
            var sidebar = document.getElementById('sidebar');
            sidebar.classList.toggle('collapsed');
        });
    </script>
</body>
</html>
